env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - react
  - react-hooks
rules:
  linebreak-style:
  - error
  - unix
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/jsx-uses-react: error
  react/react-in-jsx-scope: off
  react/jsx-uses-vars: error
  react/display-name: off
